/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#e1e2e7',
        primary: '#fbfffa',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
        surface: '#111417',
        'surface-variant': '#323539',
        error: '#ffb4ab',
        secondary: '#d6baff',
        'inverse-on-surface': '#2e3134',
        'tertiary-container': '#9ffa00',
        'on-error': '#690005',
        'on-secondary-container': '#cba9ff',
        'inverse-surface': '#e1e2e7',
        'on-tertiary-fixed': '#102000',
        'surface-container-high': '#282a2e',
        'surface-container-low': '#191c1f',
        'error-container': '#93000a',
        'on-surface-variant': '#b9cbc1',
        'surface-container': '#1d2023',
        'secondary-fixed-dim': '#d6baff',
        'primary-fixed-dim': '#00e1ab',
        'on-secondary-fixed': '#280057',
        'surface-dim': '#111417',
        'on-primary-fixed-variant': '#00513c',
        'primary-fixed': '#36ffc4',
        'on-tertiary': '#1f3700',
        'on-primary-container': '#007255',
        'inverse-primary': '#006c50',
        background: '#111417',
        'surface-tint': '#00e1ab',
        'secondary-container': '#6205c3',
        'secondary-fixed': '#ecdcff',
        'primary-container': '#00ffc2',
        'on-secondary': '#430089',
        'on-tertiary-container': '#446f00',
        tertiary: '#fefff4',
        outline: '#83958c',
        'on-secondary-fixed-variant': '#6000bf',
        'surface-container-highest': '#323539',
        'on-primary': '#003828',
        'tertiary-fixed-dim': '#8bdc00',
        'on-tertiary-fixed-variant': '#2f4f00',
        'on-primary-fixed': '#002116',
        'tertiary-fixed': '#9ffb00',
        'outline-variant': '#3a4a43',
        'on-background': '#e1e2e7',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
        mono: ['JetBrains Mono'],
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
